### ISSUE TITLE
Running concourse under root is broken

### ISSUE THREAD

**Issue by rnurgaliyev** [ahelal/ansible-concourse#29]
If you want to run concourse under root user, so it could listen on ports below 1024, role will try to modify root user which is not a good thing. Probably system user related stuff should be taken away from this role completely.

`fatal: [concourse-open-web000]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "append": false, 
            "comment": null, 
            "createhome": true, 
            "expires": null, 
            "force": false, 
            "generate_ssh_key": null, 
            "group": "root", 
            "groups": null, 
            "home": "/opt/concourseci", 
            "login_class": null, 
            "move_home": false, 
            "name": "root", 
            "non_unique": false, 
            "password": null, 
            "remove": false, 
            "seuser": null, 
            "shell": null, 
            "skeleton": null, 
            "ssh_key_bits": 0, 
            "ssh_key_comment": "ansible-generated on concourse-open-web000", 
            "ssh_key_file": null, 
            "ssh_key_passphrase": null, 
            "ssh_key_type": "rsa", 
            "state": "present", 
            "system": true, 
            "uid": null, 
            "update_password": "always"
        }, 
        "module_name": "user"
    }, 
    "msg": "usermod: user root is currently used by process 1\n", 
    "name": "root", 
    "rc": 8
}
`

**Comment by ahelal** [comment]
@rnurgaliyev I am not sure running it under root is a good idea to begin with. I would recommend using a redirect to a non privileged port using nginx or haproxy or any other solution.

**Comment by ahelal** [comment]
please open a PR if you still need this
