### ISSUE TITLE
CONCOURSE_WORKER_NAME should be omitted from default configuration

### ISSUE THREAD

**Issue by rnurgaliyev** [ahelal/ansible-concourse#33]
CONCOURSE_WORKER_NAME environment variable should not have default value and should be omitted if not set apparently. Concourse worker will then pick system host name for its name. If concourse is pre-built in bootstrap image, e.g. with packer, all workers will end up with same id coming and will fail to register.

**Comment by ahelal** [comment]
@rnurgaliyev tests are failing, because of retire script, can you do a fallback ?

**Comment by ahelal** [comment]
#35 should fix this i guess
