### ISSUE TITLE
Specifying multi arg vars seems impossible

### ISSUE THREAD

**Issue by slapers** [ahelal/ansible-concourse#50]
Hi,

It looks as if specifying web options that are repeatable, such as CONCOURSE_VAULT_AUTH_PARAM (--vault-auth-param=NAME=VALUE) are impossible...
Probably specifying these is only possible through commandline args ?

I currently circumvented this by creating a variable called `concourse_web_args` which looks like this:

```
concourse_web_args: [
  "--vault-auth-param=role_id={{ vault_role_id | default('na') }}",
  "--vault-auth-param=secret_id={{ vault_secret_id | default('na') }}"
]
```

I modified the `concourse-web.j2` template, changing the last line:

```
exec {{ concourseci_bin_dir }}/concourse web {{ concourse_web_args | default([]) | join(' ')}} >> {{ concourseci_log_web }} 2>&1
```
Is there a better way to solve this ?

**Comment by ahelal** [comment]
Not 100% sure, but looking into [go-flags](https://github.com/jessevdk/go-flags) that is used by concourse. You can pass slices and maps. So my suggestion is to try to use `CONCOURSE_VAULT_AUTH_PARAM="a:2;b:3"` 
I got that from the [tests](https://github.com/jessevdk/go-flags/blob/master/parser_test.go) 

Do let me know if that works.

Cheers

**Comment by slapers** [comment]
Awesome, the format that seems to work is: `CONCOURSE_VAULT_AUTH_PARAM="role_id=xxx,secret_id=yyy"`

Thanks for pointing me in the right direction !

**Comment by ahelal** [comment]
👍
