### ISSUE TITLE
127.0.0.1 connect refused in vagrant vm

### ISSUE THREAD

**Issue by jeff1985** [ahelal/ansible-concourse#52]
I started testing this playbook by spinning a local vm with vagrant:
vagrant up

To test the functionality i checked out the concouse tutorial:
    git clone https://github.com/starkandwayne/concourse-tutorial.git
    cd concourse-tutorial

I'm able to login with the fly cli:
fly --target tutorial login --concourse-url http://192.168.50.150:8080
fly --target tutorial sync

The first task 01_task_hello_world runs as intended. But when I try to run the second task (02_task_inputs), it fails:  

    $ fly --target tutorial execute --config inputs_required.yml --input some-important-input=.   
    executing build 6 at http://192.168.50.150:8080/builds/6 
    upload request failed: Put http://127.0.0.1:8080/api/v1/pipes/53a36768-4d3a-4034-49d1-1fc2d5305c04: dial tcp 127.0.0.1:8080: getsockopt: connection refused
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 
     127.0.0.1 port 8080: Connection refused
    gzip: stdin: unexpected end of file
    tar: Child returned status 1
    tar: Error is not recoverable: exiting now
    exit status 2
    failed

This will not happen, if I use the concourse vagrant box provided by the tutorial itself. So there must be some issue within this playbook.

**Comment by ahelal** [comment]
Hi @jeff1985, 

Found the bug and it is resolved with PR #56 the bug was vagrant was using default config of external url `127.0.0.1:8080` instead of the vagrant `192.168.50.150:8080`

Thanks for reporting it 👍
