### ISSUE TITLE
vagrant up gives error on running default ansible-playbook

### ISSUE THREAD

**Issue by devdavidkarlsson** [ahelal/ansible-concourse#6]
ERROR: expected a role name in dictionary: {'name': 'hosts', 'tags': 'hosts'}
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by ahelal** [comment]
HI @devdavidkarlsson  Can you please provide more context 
ansible version and vagrant version
debug data
`vagrant provision --debug`

**Comment by ahelal** [comment]
@devdavidkarlsson  this should be fixed in master. I did not do a release yet since it's still experimental. Please feel free to reopen ticket if you still are facing issues
