### ISSUE TITLE
Installing concourse >=6.2.0 fails

### ISSUE THREAD

**Issue by akshaymankar** [ahelal/ansible-concourse#84]
Since v6.2.0, concourse treats [env variables more strictly](https://github.com/concourse/concourse/releases#strict-env-vars). The role sets `CONCOURSE_SESSION_SIGNING_KEY` and `CONCOURSE_TSA_HOST_KEY` env variables, which are not required to run concourse workers and the files don't exist on the disk. This can be fixed by removing [these two lines](https://github.com/ahelal/ansible-concourse/blob/168e36071a8f992fa01acc95b4cf2d4a927089a6/defaults/main.yml#L61-L62).

**Comment by akshaymankar** [comment]
> This can be fixed by removing [these two lines](https://github.com/ahelal/ansible-concourse/blob/168e36071a8f992fa01acc95b4cf2d4a927089a6/defaults/main.yml#L61-L62).

This is not true, those variables are being used in other places, so the solution would be more complicated like having separate env variables for the public keys for TSA and session signing to make sure these web specific env variables don't end up on the worker machines.

**Comment by ahelal** [comment]
@akshaymankar I am open for a PR 👍

**Comment by xeivieni** [comment]
@akshaymankar any updates ?

**Comment by akshaymankar** [comment]
I haven't been able get time for this yet. I don't think I will get time at least in the next month or so.

**Comment by xeivieni** [comment]
Okay, I have a bit of time, let me take care of this.

**Comment by xeivieni** [comment]
#86

**Comment by ahelal** [comment]
thanks merged

**Comment by xeivieni** [comment]
Hi @ahelal, can you release our fix ? We use tags for installing your role 

Moreover, if think you can close this issue now
